name: Update deploy branch with dist folder contents

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory
    branches:
    - master # Only trigger on the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: bundle exec jekyll build
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        publish_dir: ./_site
        publish_branch: deploy
